version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/app"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/app"
    schedule:
      interval: "weekly"
